# Etapa de build
FROM node:18-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm install "@react-spring/parallax" react-icons react-dom swiper
COPY . .
RUN npm run build

# Etapa de produção
FROM nginx:alpine
EXPOSE 80

# Copiando o build gerado para o diretório do nginx
COPY --from=build /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
