services:
  reactvite:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  springio:
    build:
      context: ./backend/microservices
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ENV_GROUP: EnvService
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
