services:
  reactvite:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    volumes:
      - ./frontend/dist:/var/www/html/frontend
    networks:
      - network

  springio:
    build:
      context: ./backend/microservices
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - network

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - network

networks:
  network:
    driver: bridge
