services:
  reactvite:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    networks:
      - network

  springio:
    build:
      context: ./backend/microservices
      dockerfile: Dockerfile
    ports:
      - "81:81"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - network

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - network

networks:
  network:
    driver: bridge
