services:
  reactVite:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  springIO:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ENV_GROUP: EnvECommerce
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
