name: Deploy Application WebServices
on:
  push:
    branches: [PortifolioWebServices]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
